name: Unit Tests

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test